### PR TITLE
Fix installation script curl issue.

### PR DESCRIPTION
**Pull request by andrievsky**
It fails on windows and blocks cocos creator sdkbox ui with the exception:
ERROR! url:http://download.sdkbox.com/installer/v1/manifest.json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 403, in <module>
  File "<string>", line 386, in main
  File "<string>", line 346, in get_installer_url
Exception: ERROR! load manifest fail

### CODE REVIEW

**Comment by yinjimmy** [comment]
how to reproduce this issue? Network traffic?

**Comment by andrievsky** [comment]
You could represent it with `curl -v http://download.sdkbox.com/installer/v1/manifest.json` to find **content-length** header missed.
I have updated the pr with respect to this fact and supporting downloading progress visualization if possible.

**Comment by andrievsky** [comment]
Would you like to be so nice to review the PR or do you need any additional info?

**Comment by andrievsky** [comment]
@yinjimmy Any news so far?

**Comment by hugohuang1111** [comment]
Need to compare in a case-insensitive way?

```python
if(response.headers.has_key('content-length'))
```

**Comment by andrievsky** [comment]
Header names are not case sensitive.
https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

**Comment by hugohuang1111** [comment]
looks fine.

**Comment by yinjimmy** [comment]
Thanks

**Pull request merged**
