### PR TITLE
2015 09 21 fixes

### PR DESCRIPTION
**Pull request by slackmoehrle**
fixed some formatting issues.

### CODE REVIEW

**Comment by nitling** [comment]
If the `project.properties` section is the same why we need to separate them to create duplication?

**Comment by slackmoehrle** [comment]
consistency. We share similar steps in separate files for other plugins too. Like when Google Play Services is shared.

**Comment by nitling** [comment]
If we have duplications we have to remember to change all the duplicated parts. And that is the major reason for inconsistency before we switch to the web document.

**Comment by slackmoehrle** [comment]
I agree. We have other places we need to change too to eliminate the duplicates.

**Comment by sdkbox-doc** [comment]
If we agree that duplication is bad, please eliminate duplication whenever possible, also avoid creating duplication if possible.

**Comment by slackmoehrle** [comment]
Yeah, I can add a task to pivotal. There are a handful of places where we still have exact duplicated content.

**Comment by nitling** [comment]
Sure, but what's your suggestion for this one?

**Comment by slackmoehrle** [comment]
If you can cherry pick just the first 2 items, or, we can discard this PR and I can make the first 2 changes again. No big deal.

**Comment by nitling** [comment]
I can do the cherry-pick

**Comment by nitling** [comment]
Cherry-picked with #52

**Pull request closed without merging**
